# Generated by Django 5.1 on 2024-08-31 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_remove_project_contributors_remove_project_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='rating',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='role',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
