# Generated by Django 5.1 on 2024-10-19 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_testimonial_rating_testimonial_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='featured',
        ),
    ]
